name: CI
on:
  push:
  workflow_dispatch:
jobs:
  puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-xcb1 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2 xvfb
          yarn install
          git submodule init
          git submodule update
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Install Chrome r1095492
        run: |
          wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1095492%2Fchrome-linux.zip?alt=media -O chrome.zip
          unzip chrome.zip
          pwd
      # - name: Set up Node.js v18.14.2
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.14.2
      - name: Test Code
        uses: mujo-code/puppeteer-headful@18.9.0
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/local/share/chrome-linux/chrome
          PUPPETEER_HEADLESS: "false"
          DISPLAY: ":99"
          CI: "true"
        with:
          args: yarn start https://uad.ubq.fi/
