name: CI
on:
  push:
  workflow_dispatch:
jobs:
  puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-xcb1 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2 xvfb
          yarn install
          git submodule init
          git submodule update
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Install Chrome r1095492
        run: |
          wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1095492%2Fchrome-linux.zip?alt=media -O chrome.zip
          unzip chrome.zip && rm chrome.zip && mv chrome-linux /usr/local/share/
          ln -s /usr/local/share/chrome-linux/chrome /usr/bin/google-chrome-stable
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
          PUPPETEER_HEADLESS: "false"
          DISPLAY: ":99"
          CI: "true"
        with:
          args: yarn start https://uad.ubq.fi/
