name: CI
on:
  push:
  workflow_dispatch:
jobs:
  puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-xcb1 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2 xvfb
          yarn install
          git submodule init
          git submodule update
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Launch browser
        run: yarn start https://uad.ubq.fi
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
          PUPPETEER_HEADLESS: "false"
          DISPLAY: ":99"
      # - name: Run tests
        # run: yarn test
